### ISSUE TITLE
How to implementate the weighted sum operation using Conv1D? 

### ISSUE THREAD

**Issue by moximoxihu** [shivam-grover/S3-TimeSeries#2]
The authors mention using Conv1D to implement the weighted sum operation in the paper,  but do not provide a specific implementation in the code (or I may have overlooked it). 

Based on my understanding, using Conv1D to implement the weighted sum operation contains the following steps:

```
x = weight1 * x + weight2 * S3(x) # weight1 and weight2 are learnable parameters.
x = CNN1D(x)
preditions = mymodel(x) # mymodel is the task-specific model.
```
Are these steps correct?
Looking forward to your feedback.

**Comment by shivam-grover** [comment]
Thank you for your interest!

If you look at the lines below, the weighted average using Conv1D has already been implemented. You need to set use_conv_w_avg=True when creating the S3 layers. 

**initialization**: https://github.com/shivam-grover/S3-TimeSeries/blob/main/S3/S3.py#L100
**Usage**: https://github.com/shivam-grover/S3-TimeSeries/blob/main/S3/S3.py#L261

We first transform the two sequences to be in a single tensor of shape `(b * t * c, 2, 1)`. When you send this through a Conv1D with `kernel_size=1`, and `in_channels=2`, `out_channels=1`, it essentially performs a weighted average and outputs a tensor of shape `(b * t * c, 1, 1)` which can be reshaped back to the original tensor's, i.e. `(b, t, c)`.

The other way to do this is using a simple linear layer with 2 weights.
https://github.com/shivam-grover/S3-TimeSeries/blob/main/S3/S3.py#L105

While using a Linear layer or a Conv1D layer for this should not have any difference since the operations are exactly the same, experiments show otherwise. Below is a good StackOverflow thread to read on this. The answer by Hanchen (the second answer from what I can see) shows that the outputs can vary, especially with deeper networks, and the gradient backpropagation updates also differ.

https://stackoverflow.com/questions/55576314/conv1d-with-kernel-size-1-vs-linear-layer
